# permissions for end users to view myconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myconfig-viewer-role
rules:
- apiGroups:
  - simple.absa.subatomic
  resources:
  - myconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simple.absa.subatomic
  resources:
  - myconfigs/status
  verbs:
  - get
